### ISSUE TITLE
Does this work for web?

### ISSUE THREAD

**Issue by Gee5ive** [Instawork/hyperview#17]
First. thanks for the amazing framework you guys have created.

I was wondering if this works for web as well, and if not, are there any plans on porting it to web so you can write once and run it everywhere?

Thanks.

**Comment by adamstep** [comment]
Thanks @Gee5ive !

The framework doesn't work on the web right now. We're still focused on making Hyperview feature-complete on mobile before we would consider porting it to web. One approach may involve using [react-native-web](https://github.com/necolas/react-native-web) to get the React Native client working in the browser.

At Instawork, we currently use [Intercooler.js](http://intercoolerjs.org/) on the web to get a similar developer experience to Hyperview. Although we can't re-use 100% of the code, much of the server-side code gets reused, with the differences being limited to the view (template) layer.

**Comment by Gee5ive** [comment]
@adamstep using react native web was exactly what  I was thinking. I don't mind using intercooler for the web, but I was hoping for something along the lines of [reactXP](https://microsoft.github.io/reactxp/).

One other thing, how is styling taken care of using this framework? I don't see it mentioned anywhere in the docs?

**Comment by mikailcetinkaya** [comment]
There is styling example in demo

**Comment by terryatgithub** [comment]
hi @adamstep adam, we are now also facing such a demand: 
we need to deploy the App developed based on Hyperview to the web side. 

Now we have two ideas:
1. Completely redevelop a web version.
2. Rewrite a HTML page on the server, which corresponds to the original XML page one by one.
Both above ideas take time and efforts.

Do you have any suggestions for this requirement?
Is intercooler.js mentioned above the silver bullet? 
if not, is the second idea better or more practical or not? 
Thank you very much.

**Comment by terryatgithub** [comment]
thank you Adam.
We will do some research on the points you mentioned, and maybe some POC.
Will share it if there is some progress.

**Comment by terryatgithub** [comment]
hi @adamstep , I'm now testing the Hyperview in react-native-web project, and met the following errors ( compatbility issue of web).  
<img width="818" alt="image" src="https://user-images.githubusercontent.com/12246394/166924870-6cf7ca44-343f-4ce9-aedd-a53f6297dcb2.png">

Since our project needs to support the web version with minimum cost, I plan to fix the Hyperview web compatibility issues encountered, and consider filing a PR if it goes well.
Do you think this is ok? Is it possible to consider supporting the web? 

Thank you and looking forward to your reply.
