### ISSUE TITLE
Does Hyperview support RTL languages and RTL layout?

### ISSUE THREAD

**Issue by rock59** [Instawork/hyperview#186]
Does Hyperview support RTL languages and RTL layout?

**Comment by adamstep** [comment]
Hi @rock59 , since Hyperview is built on top of React Native, it is possible to support RTL as described here: https://reactnative.dev/blog/2016/08/19/right-to-left-support-for-react-native-apps

However, Hyperview does not expose access to [I18nManager](https://github.com/facebook/react-native/blob/f0fb228ec76ed49e6ed6d786d888e8113b8959a2/Libraries/Utilities/I18nManager.js), in order to change logic or images depending on language layout. This decision can be made server-side when rendering the XML.
