### ISSUE TITLE
any suggestion on how to add dynamic graph into the screen? like bar/pie chart base on some data from server side

### ISSUE THREAD

**Issue by cengit** [Instawork/hyperview#204]
hi, this is a really great lib!!!
but i'm noticing there is no graph in the demo, can you tell me how to add dynamic graph into the screen?
for example: if i want some screen have a bar/pie chart base on some data from server side, what should i do?

another question: for some reason, if i want to change some screen with React-native UI (like page a is hyperview, and navigate to page b which is react-native page), is it possible?

**Comment by adamstep** [comment]
Hi @cengit, answers below:

> hi, this is a really great lib!!!
> but i'm noticing there is no graph in the demo, can you tell me how to add dynamic graph into the screen?
> for example: if i want some screen have a bar/pie chart base on some data from server side, what should i do?

There are a couple of approaches here that can work by extending your Hyperview app with custom elements. Check out the docs here: https://hyperview.org/docs/reference_custom_elements

For example, you could find a React Native library for charts & graphs, and create a custom Hyperview element from it. Then you'd just pass the data & config to the custom element from the server, and the chart would render on your Hyperview screen.

We've done this in our own app for Google Maps and SVG images. The custom element for SVG makes use of the `react-native-svg` library and looks something like this:
```js
import React, { PureComponent } from 'react';
import type { Props } from './types';
import { SvgXml } from 'react-native-svg';

export default class HyperviewSvg extends PureComponent<Props> {
  static namespaceURI = 'http://www.w3.org/2000/svg';
  static localName = 'svg';
  props: Props;

  render() {
    const parsedWidth: number = parseInt(this.props.element.getAttribute('width'), 10);
    const parsedHeight: number = parseInt(this.props.element.getAttribute('height'), 10);
    const width: number = Number.isNaN(parsedWidth) ? 0 : parsedWidth;
    const height: number = Number.isNaN(parsedHeight) ? 0 : parsedHeight;
    return <SvgXml height={height} width={width} xml={this.props.element.toString()} />;
  }
}
```

> 
> another question: for some reason, if i want to change some screen with React-native UI (like page a is hyperview, and navigate to page b which is react-native page), is it possible?

This is possible, in fact we do this often in the Instawork app because we have several screens written in RN before adopting Hyperview. Does your RN app use Redux? If so, you can add a custom behavior to dispatch Redux actions from Hyperview pages. Check out https://hyperview.org/docs/reference_custom_behaviors#redux-actions for an example of the custom behavior and an example of how to use it. Once you dispatch a Redux action, your RN page can re-render based on the change and do a navigation if needed.

Let me know if that makes sense, happy to provide more information.

**Comment by cengit** [comment]
@adamstep thanks for the reply, awesome features as your example provided, I will definitely have a try.

thanks again!
