### ISSUE TITLE
How to send http post request from hyperview xml to java backend controller?

### ISSUE THREAD

**Issue by Alina-Cui** [Instawork/hyperview#205]
Hi genius, I have read the guide of basic form  section here https://hyperview.org/docs/example_basic_form. But I fond some issues.
1. Even if I use the "verb=post" property in xml it send a "GET" request. 
2. When I play with the case study examples of  basic form section, after I click the Submit button whithout nothing input I got the bellow error.
![image](https://user-images.githubusercontent.com/74521001/99209142-6e8ee600-27fd-11eb-8a1d-b1549b87fa37.png)
![image](https://user-images.githubusercontent.com/74521001/99209106-4dc69080-27fd-11eb-821e-20dd83a158af.png)

3. How to send http post request from hyperview xml to java backend controller?

My system version is Macos catalina 10.15.6. The simulator version is Iphone11pro-14.1

Could you pls help on above questions?

**Comment by adamstep** [comment]
@Alina-Cui I see you closed this issue, did you solve the problem? If so, what was the solution?

**Comment by Alina-Cui** [comment]
I can get the "POST" request only when I use "replace" syntax like bellow code. When i use "push" it will send a "GET" request
```
           <view action="replace"
                  href="/createGoal"
                  verb="post"
                  target="createGoal"
                  show-during-load="mySpinner"
                  style = "Button">
              <text style="Button__Label">Setup this goal</text>
            </view>
```
 But i can not get the body of the post. The param is send across the requestParam instead of the post body.

**Comment by adamstep** [comment]
Hi @Alina-Cui , this is currently part of the design of Hyperview. The reason is that if the POST request fails (invalid data), we want to render the error on the same screen rather than pushing a new error screen onto the stack. That's why navigation (sliding in a new screen or modal) only work with GET.

What I recommend doing is making a POST request with `replace` like you mention. If the POST is successful, the response can include a behavior to slide in the new page:
```xml
<view
  xmlns="https://hyperview.org/hyperview"
  trigger="load"
  href="/new_page"
/>
```

There's an example of this approach on the Hyperview website: https://hyperview.org/docs/example_delayed_navigation
