### ISSUE TITLE
Question: Can parameters be passed to a screen?

### ISSUE THREAD

**Issue by saary** [Instawork/hyperview#333]
Imagine an itemized list of dishes, when you press on a dish you are presented with a full screen image of that dish.

Theoretically I could return a `<screen>` for the list together with a set of `<screen>` per dish. and then navigate to the relevant dish image on press.

However it seems a bit wasteful to send all the screens in advance. I'd rather use a "template" screen where I can pass certain parameters to and it will render with the given parameters.

Can it be achieved?

**Comment by adamstep** [comment]
Hi @saary . Hyperview does not support client-side templating, so you would need to send each dish screen separately. Or, you could make a HTTP request for the dish screen when the user taps the item in the list. 

Instead of client-side templating, we support [custom elements](https://hyperview.org/docs/reference_custom_elements). You could create a custom element to render the full screen dish image, and use XML attributes to pass the URL of the image and any other parameters. This would reduce the repetition in your markup.

**Comment by saary** [comment]
Thank you for the response, the custom element sounds like an elegant solution. I'll take a look.
