### ISSUE TITLE
Django Integration and deploy on android apk

### ISSUE THREAD

**Issue by uncion7** [Instawork/hyperview#474]
Thank for excellent project. Please share a tutorial how we can to work with django (python) and create an apk for android.

**Comment by adamstep** [comment]
Hi @uncion7 .

We use Django at Instawork to serve our Hyperview app. There's nothing special you need to do. In your Django view, just return the XML content instead of HTML. In fact, we use Django's template library to render the Hyperview XML. To test your Django implementation, you can use the demo app that comes in this repo (see the [README](https://sentry.io/organizations/instawork/issues/3533975555/?query=is%3Aunresolved)). You will need to point it to your local Django app by changing [this setting](https://github.com/Instawork/hyperview/blob/master/demo/src/constants.js#L2).

To create an APK for Android, I recommend you start with the demo app in this repo as your base app. The demo app is based on Expo, which has instructions for building and installing an Android APK: https://docs.expo.dev/build-reference/apk/
